on:
  # Trigger analysis when pushing to main or an existing pull requests.  Also trigger on
  # new pull requests
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Common Workflow
jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    # check out project
    steps:
    - uses: actions/checkout@v3.0.2
    # steps to build the artifact you want to scan
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: build
      run: ./mvnw clean install -DskipTests=true
    # ...
    # Scan Artifact    
    # - name: Contrast Scan Action
    #   uses: Contrast-Security-OSS/contrastscan-action@v2.0.2
    #   with:
    #     artifact: webgoat-server-8.2.2.jar
    #     apiKey: ${{ secrets.CONTRAST_API_KEY }}
    #     orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
    #     authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
    #Upload the results to GitHub      
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
